### ISSUE TITLE
r.RequestURI vs r.URL.Path

### ISSUE THREAD

**Issue by claudiofelber** [dimfeld/httptreemux#12]
Is there a reason that you are using `r.RequestURI` instead of `r.URL.Path`. The problem with `r.RequestURI` ist that it does not work with `http.StripPrefix`, so the following code always returns a 404 because it does not notice that the "admin" prefix has been stripped off the path (`http.StripPrefix` does only modify `r.URL.Path`):

```go
mux := httptreemux.New()
mux.GET("/", getIndex)
mux.GET("/users", getUsers)
mux.GET("/users/:id", getUser)
http.Handle("/admin/", http.StripPrefix("/admin", mux)
```

**Comment by dimfeld** [comment]
This is the reason: https://code.google.com/p/go/issues/detail?id=3659

It should be pretty simple to make a config option to use r.URL.Path instead; I already have some code to do that if RequestURI is empty, which can happen with certain test code, so it should be easy to adapt that. I'll be glad to accept a PR if you want to take this on; otherwise I should probably have time next week to take care of it.
