### ISSUE TITLE
Allow params in concurrent paths to be different

### ISSUE THREAD

**Issue by solher** [dimfeld/httptreemux#13]
Hi, thanks for your work on httptreemux.

I just noticed that the paths `/users/:pk/:related` and `/users/:id/updatePassword` cannot exist concurrently. The first param must be identical (:pk or :id but not both).

Would it be possible to easily solve the problem ? I think it should not change the behavior but if it is too complicated...

Thanks !

**Comment by dimfeld** [comment]
I can think of a couple ways to do this; the faster of the two ways would require the leaf nodes in the tree to hold some information about the names of the earlier wildcard parameters, so that the correct names can be assigned. This isn't a super-simple change, but probably not that bad to implement. I'll look into it.

**Comment by solher** [comment]
Ok thanks a lot !
