### ISSUE TITLE
Serving static file directory

### ISSUE THREAD

**Issue by patrickrand** [dimfeld/httptreemux#14]
Hi,

I am having issues attempting to serve a directory of static files in conjunction with other handlers.

I have a series of handlers such as: 
```golang
	ws.Handle("GET", "/apidocs/", SwaggerHandler)
	ws.Handle("GET", "/:namespace", GetAllUniqueHandler)
	ws.Handle("GET", "/:namespace/:name", GetAllVersionsHandler)
	ws.Handle("GET", "/:namespace/:name/:version", GetVersionHandler)
    ....
```
where the ```SwaggerHandler ``` is defined as follows:

```golang
func SwaggerHandler(ctx *Context) (err error) {
	http.StripPrefix("/apidocs/",
		http.FileServer(
			http.Dir("/<absolute>/<path>/<to>/<my-files>/")))
	return
}
```

I've read through your code-base and docs, and tried setting ```ws.TreeMux.PathSource = httptreemux.URLPath``` as recommended, but I still have no luck. All of my non-static file handlers work perfectly, but my ```SwaggerHandler``` just returns an empty page. 

Do you have any insight on what I may be doing wrong, or how I may resolve this issue?

Thank you.

**Comment by dimfeld** [comment]
I think the problem is that your first route needs a catchall. That is, it should look like this:
```
ws.Handler("GET", "/apidocs/*path", SwaggerHandler)
```

Without the catchall, the router will only match on `/apidocs/`, but a path such as `/apidocs/README.md` would actually match on `/:namespace/:name`. I think that should be the only change needed. Hope this helps!
