### ISSUE TITLE
use for non-http

### ISSUE THREAD

**Issue by pjebs** [dimfeld/httptreemux#67]
Is there a way to use this for non-http scenarios. I only need the path routing implementation. i.e. string -> parse -> call a function based on arguments in "route" path

**Comment by dimfeld** [comment]
Not out of the box, but pretty much all the logic you want is contained in `tree.go` so you could copy that file and use it in your project. Its interface isn't really designed for external usage, so you would probably want to write a few wrapper functions around the code snippets below to make it nicer to use.

With the caveat that I haven't tried it, I think something like this should work:

First, instantiate the root of the tree.
```
root := &node{ path: "/" }
```

Then add routes to it. 

```
n := root.addPath("a/path/with/:wildcard/:anotherWildcard", nil, false)
n.setHandler("GET", myFunction, false)
```
Here I'm just calling it with the `GET` method all the time to keep things simple. For reference, here's the original code with all the extra HTTP stuff that you don't need.
https://github.com/dimfeld/httptreemux/blob/a454a10de4a11f751681a0914461ab9e98c2a3ff/group.go#L96-L106 

And later look it up (removing the leading slash if there is one)
```
path := "/a/path/with/a/value"
n, handler, params := root.search("GET", path[1:])
```

Then process the results. 
```
if n != nil {
  // Found it!
  // params[0] == "a" and params[1] == "value". 
  handler(params)
}
```
The returned wildcard parameters are in a slice by default. The code to make these into a map with named parameters, if you want, is https://github.com/dimfeld/httptreemux/blob/a454a10de4a11f751681a0914461ab9e98c2a3ff/router.go#L188-L201

These snippets don't take into account the trailing slash behavior, so if you care about that you can find the relevant parts throughout the code base by searching for `trailingSlash` and `addSlash`.

You would also want to change the various references to HandlerFunc to be whatever function prototype you want, and depending on how much work you want to do, maybe remove all the HTTP method specific stuff in `tree.go`, which mostly entails changing `leafHandler` into just a single function type instead of a map.

Hope this helps!

**Comment by pjebs** [comment]
how would I add a mutex so i can modify the routes at runtime?

**Comment by dimfeld** [comment]
Same as anything else that needs thread safety. Wrap the calls to add new routes and the calls to search with an RWMutex or whatever you deem most appropriate. The router already has an option to do this so you can see how it does it by looking through the code.

**Comment by pjebs** [comment]
thank you @dimfeld
