### ISSUE TITLE
Posting a html form doesn't work with trailing slash redirect.

### ISSUE THREAD

**Issue by kabukky** [dimfeld/httptreemux#7]
Hi,
thanks for making this router. I'm trying it out right now.
However, I encountered this weird behavior:

I have a html form that does a POST to `/admin/register/` (notice the trailing slash).

When I use httptreemux like this:

    router.GET("/admin/register", getRegistrationHandler)
    router.POST("/admin/register", postRegistrationHandler)

the `postRegistrationHandler` isn't called.

But when I use httptreemux like this:

    router.GET("/admin/register", getRegistrationHandler)
    router.POST("/admin/register/", postRegistrationHandler)

it works just fine.

This seems to be a problem with redirection, right? Maybe because I defined the GET method without a trailing slash?

Thanks

**Comment by dimfeld** [comment]
The router returns a 301 redirect to make the browser point to the correct trailing slash. I did a bit of research and it appears that in this case the browser will just do a GET request to the redirected location instead of a POST with the original data. Is this the case that you're seeing?

If so, I think the best solution here is to add an option to the router to not do a redirect, but instead to just call the handler. I might have time to add such a feature this week, but not sure yet. If you'd like to take it on and submit a pull request I'll be glad to look it over.

**Comment by kabukky** [comment]
Hi dimfield,
that is exactly what my browser is doing.
That option would be a nice feature to have. You can take your time with it though, I'll just make sure to always use correctly formatted urls for now :)

Thanks!

**Comment by dimfeld** [comment]
Quick update, I have some code written to make the redirect behavior more flexible, including an option to just call the handler like you want. Still need to write tests and update the docs for it which I hopefully will get to do some time next week.

**Comment by kabukky** [comment]
That sounds good.
I'm using httptreemux as the default mux for [Journey](https://github.com/kabukky/journey) now - works great! :)
