### ISSUE TITLE
Always put the params in request Context when a middleware stack contains an http.Handler

### ISSUE THREAD

**Issue by dimfeld** [dimfeld/httptreemux#73]
This allows us to not have to resintantiate the middleware on every call since we won't need to pass a `next` function that closes around `params`.

**Comment by nightlyone** [comment]
I just ran into this while implementing tracing middleware.
Middleware seems to have no access on the matched route and the params provided.

The reason seems to be that the context is filled in some kind of implicit middleware that always runs last: https://github.com/dimfeld/httptreemux/blob/v5.2.2/context.go#L68

**Comment by ninthclowd** [comment]
taking a stab at resolving this with #81

**Comment by dimfeld** [comment]
Fixed by #81 and #82. Thanks!
