### ISSUE TITLE
How to best serve sub folders and files?

### ISSUE THREAD

**Issue by kabukky** [dimfeld/httptreemux#9]
Hi,
I'd like to serve everything that is present in folder called `pages`. Here's a sample structure:
```
|____pages
| |____webgl
| | |____Compressed
| | | |____webgl-export.jsgz
| | |____index.html
| | |____Release
| | | |____fileloader.js
| | |____TemplateData
| | | |____default-cover.jpg
| | | |____favicon.ico
```
Here's what I'm doing with httptreemux:
```
func pagesHandler(w http.ResponseWriter, r *http.Request, params map[string]string) {
	http.ServeFile(w, r, filepath.Join("pages", params["filepath"]))
	return
}

func InitializePages(router *httptreemux.TreeMux) {
	// For serving standalone projects or pages saved in in content/pages
	router.GET("/pages/*filepath", pagesHandler)
}
```
This works fine when I open e. g. `http://server.url/pages/webgl/Release/fileloader.js`.

However, `http.ServeFile` is supposed to serve the `index.html` when opening `http://server.url/pages/webgl/`.
It does that, but the path will be rewritten to the one without a trailing slash (`http://server.url/pages/webgl`).
This breaks links to files and sub folders in the `index.html`, e.g.:
```
<script src="Release/fileloader.js"></script>
```
which will now link to `http://server.url/pages/Release/fileloader.js` instead of `http://server.url/pages/webgl/Release/fileloader.js`.

Thanks
Kai

**Comment by dimfeld** [comment]
Ah, that's interesting. As you've surmised, I don't think there's currently a good way to do this. 

What I have in mind is an router-level option to never do the trailing slash redirect for paths with a catch-all at the end. I might actually make that the default behavior, since the current behavior in this case doesn't really make much sense, and I suspect there isn't anyone depending on it working how it does now.

I should be able to get this to you by next week, but maybe earlier. Hope that works :)

**Comment by kabukky** [comment]
That's totally fine. Thanks for taking this on :)

**Comment by dimfeld** [comment]
Ended up with a bit of time so I implemented this. Thanks for all your feedback!

**Comment by kabukky** [comment]
Wow, you're fast! This works as imagined. Thank you!
